### ISSUE TITLE
form does not validate the captcha field

### ISSUE THREAD

**Issue by thinze** [thomasrawiel/powermailcaptcha#1]
Typo3: 10.4.31
Powermail: 8.4.2
Powermailcaptcha: 1.0.1
captchamethod: hcaptcha

installed by your instructions
https://github.com/thomasrawiel/powermailcaptcha#readme

in form editor (Powermail) I had added a new filed
Powermailcaptcha [powermailcaptcha]
in the tab "Extended" I had activate the "Mandatory Field" option.

no Validator , because nothing seems to match and all other are default settings

The hcaptcha field will not be validated after I click on submit. 

What is my fault or what I have to do, to enable the hcaptcha field / validation correctly.

Best regards

**Comment by thomasrawiel** [comment]
You have to add these lines as typoscript constants, not setup
```
plugin.tx_powermailcaptcha.captchaMethod = hcaptcha
plugin.tx_powermailcaptcha.sitekey = MYKEY
plugin.tx_powermailcaptcha.secretkey = MYSECRET
```

You don't need the lines beginning with
`plugin.tx_powermail.settings.captcha...` 
except if you use powermails default captcha somewhere

You don't need this
```
tx_powermail.flexForm.type.addFieldOptions {
powermailcaptcha = Powermailcaptcha
}
```
It's automatically added when the extension is active

**Comment by thinze** [comment]
The config lines are stored in constants.typoscript not in my setup.typoscript file.

I save the files twice and try again but the same result. No validation.

If it helps, I can mail you my both Typoscript files.

**Comment by thomasrawiel** [comment]
If you have the constants set and spam shield is enabled, it should work.

As I said [earlier ](https://github.com/thomasrawiel/powermailcaptcha/issues/1#issuecomment-1340923930), there is no validation per se, just a spamshield method.
If the captcha response is invalid, a value is added to the spam factor. If the spamfactor is larger than the configured threshold, a message is displayed on top the form and the form is not submitted.

Maybe try setting your spam factor higher, I tested with the default value 75
`plugin.tx_powermail.settings.spamshield.factor = 75`

**Comment by thinze** [comment]
I had modify my constants Typoscript if you wrote.
In my form definition I use the 
<img width="178" alt="image" src="https://user-images.githubusercontent.com/4058906/206211849-3d31e2b2-e996-4547-9850-3eaea366d96b.png">
no changes on tab "extented" are made, means "no mandatory", "no validator" and so on. Simply add the captcha field and set a label. Thats all.

On my form I can click on the hCaptcha checkbox and the image quest popup is visible. 
If I answered correctly the widget shows me the green checker
<img width="190" alt="image" src="https://user-images.githubusercontent.com/4058906/206212564-e2be2660-d47f-4f8d-8c13-4ab4994ab036.png">

But when I submit the form without interacting with the captcha field, there is no error message and the form is submitted.

**Comment by thomasrawiel** [comment]
Then there's maybe another problem with your configuration.

Check if the spamshield method is not overwritten by another extension

```
spamshield.methods {
        # Add recaptcha spamcheck
        10 {
            _enable = 1

            # Spamcheck name
            name = Powermailcaptcha

            # Class
            class = TRAW\Powermailcaptcha\Domain\Validator\SpamShield\CaptchaMethod

            # if this check failes - add this indication value to indicator (0 disables this check completely)
            indication = 10

            # method configuration
            configuration {
                sitekey = {$plugin.tx_powermailcaptcha.sitekey}
                captchaMethod = {$plugin.tx_powermailcaptcha.captchaMethod}
                secretkey = {$plugin.tx_powermailcaptcha.secretkey}
            }
        }
    }
```
https://github.com/thomasrawiel/powermailcaptcha/blob/main/ext_typoscript_setup.txt

You can verify this for example in the object browser (Setup):
![image](https://user-images.githubusercontent.com/5371428/206215491-2018a6c5-2d2f-4462-b1d6-554af4d44bda.png)


I will test this again with v10 and powermail 8 when I have time, but I'm pretty sure this works as we have the original extension   ext:powermailrecaptcha from where this extension is forked in multiple typo3 10 websites

**Comment by thinze** [comment]
The previous addon powermailrecapctha was installed until today. I remove this addon, update to Powermail 8.4.2 and install Powermailcaptcha 1.0.1. Possible here are the problem cause by any side effect.

My config looks like this:
<img width="382" alt="image" src="https://user-images.githubusercontent.com/4058906/206220570-49e42c14-07cb-4090-b014-8e77159f63f4.png">

and I think, that this is the reason for my problem. (no method known or registered)

**Comment by thinze** [comment]
Hmmmm ... the addon should be active
<img width="496" alt="image" src="https://user-images.githubusercontent.com/4058906/206222018-6bdc613a-709b-4b2d-bf55-d661736744a0.png">

My next try was:
- deactivate addon - reactivate addon
- flush Typo3 and PHP cache
- clear both caches (lightning icon)
- check database structure
- make a rain dance

but no method are registered in Typoscript Object Browser.

At last I add your Typoscript at last code in my constants.typoscript file:
<img width="618" alt="image" src="https://user-images.githubusercontent.com/4058906/206224790-c7d2c6c1-ee8b-4f57-9eb6-4a9a90d5a1dc.png">

clear all caches and so on, but try the sun dance instead ...
and now I see this:
<img width="379" alt="image" src="https://user-images.githubusercontent.com/4058906/206225335-d6372475-699c-4ead-9d58-453b2e0c7ebb.png">

I jump quickly to my form and re-try the submit process...
<img width="350" alt="image" src="https://user-images.githubusercontent.com/4058906/206225681-cb7cc0e1-e4b6-4741-b5a2-cb93d1efdfb7.png">
and in Typo3 Log viewer I see this:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) | ParseError thrown in file /var/www/typo3conf/ext/powermailcaptcha/Classes/Domain/Validator/SpamShield/CaptchaMethod.php in line 23. Requested URL: https://web-10000-21-001-staging.cls.pm/terminanfrage/netzhaut-op?tx_powermail_pi1%%5Baction%%5D=create&tx_powermail_pi1%%5Bcontroller%%5D=Form&cHash=43c565a90ebe45a05326163500b6508e

Can this be an PHP version problem? We use currently 7.3.28.

**Comment by thomasrawiel** [comment]
Yea that could be a problem with php. I use typed properties. I'll check if I can udpate the extension to be compatible with 7.3
(But not today)

**Comment by thinze** [comment]
BIG THX so long for your very! fast support. Have a nice day.

Meanwhile I will update our Typo3 image to V10.4.32 and PHP 7.4.

**Comment by thomasrawiel** [comment]
Yea if you update to php 7.4 the error will be fixed

**Comment by thomasrawiel** [comment]
So, as PHP 7.3 is no longer supported since 6 Dec 2021 (1 year ago) and PHP 7.2 (the minimum required version of TYPO3 10) even longer, I have decided to set PHP 7.4 as the minimum required version for this extension. Even if PHP 7.4 has reached its end of life on 28 Nov 2022 I think it's still "okay" to support.

Please upgrade to PHP 7.4 to use the latest [powermailcaptcha 1.0.2](https://github.com/thomasrawiel/powermailcaptcha/tree/1.0.2) with TYPO3 10
