### ISSUE TITLE
Selection of captcha type in flexform - make it possible to show only one option?

### ISSUE THREAD

**Issue by sypets** [thomasrawiel/powermailcaptcha#13]
Currently, you have to select a separate option in the powermail form field, so you have the powermail captcha and the powermailcaptcha captcha.

![powermailcaptcha](https://github.com/thomasrawiel/powermailcaptcha/assets/13206455/c1e86db1-aab3-4353-b24d-92f419126cc7)

## Possible solution

Ideally I would like to have **only one** captcha field for the editors to select (the default one)  and which implementation will be used is determined by admin configuration (TypoScript). This means the powermailcaptcha method would effectively override the default powermail captcha method

1. This way, we could also switch to any other captcha method in the future, either temporarily or permanently.
2. Also, I don't like to confront editors with unnecessary or potentially overwhelming choices. They should not be able to choose the CAPTCHA method. This should be chosen by admins site-wide.

## Caveat

Maybe not everyone agrees. There might be good reason to offer both CAPTCHA methods. 

## Alternative solution

Alternative solution without change in extension would also be ok. Not entirely sure how to do that currently.

I assume I could override the flexform (thus remove the default powermail field and just leave the powermailcaptcha one). I don't know how to override flexform, I vaguely remember seeing that somewhere.

If the captcha method should be changed later, the field type could be changed directly in the DB. (`tx_powermail_domain_model_field.type`).

If we choose the "alternate solution", it might be possible to add this to the documentation here.

**Comment by thomasrawiel** [comment]
You can change the available field types with TSConfig:

e.g. removing the default captcha and reset button:
`TCEFORM.tx_powermail_domain_model_field.type.removeItems = captcha,reset`

**Comment by sypets** [comment]
Thanks. Yes that works. For me, that would be sufficiently handled. Should we close?
