### ISSUE TITLE
Best practise: Use static template instead of "Preset TypoScript"

### ISSUE THREAD

**Issue by sneopu** [thomasrawiel/powermailcaptcha#19]
It would be very nice to use a static template instead of "Preset Typoscript".
See #18

**Comment by thomasrawiel** [comment]
You're probably right. It's also better to have a static template, when you have a multisite environment where you have websites that don't use powermail.

**Comment by thomasrawiel** [comment]
See https://github.com/thomasrawiel/powermailcaptcha/releases/tag/1.5.0

and thanks for the hint

**Comment by sneopu** [comment]
This was very fast! Thanks a lot.
