### ISSUE TITLE
User feedback: Suggestion to use a new major version when a breaking change occurs

### ISSUE THREAD

**Issue by lorenzulrich** [thomasrawiel/powermailcaptcha#21]
Hi Thomas

First of all, thanks for providing this extension which is very helpful.

I wanted to provide feedback on the breaking change from 1.4. to 1.5, documented here: https://github.com/thomasrawiel/powermailcaptcha/commit/b1c6e33e05a606c7ac78d3dd6f342dda52c7c2bb.

We normally trust extension maintainers to follow semantic versioning: https://semver.org/. As per semantic versioning, you can trust that in minor versions, new features may be added but there are no backwards-incompatible changes. Therefore, in the composer manifest, we e.g. set `^1.4` assuming that there won't be breaking changes within the 1.x branch.

After a quite big spam attack we found out that we updated your extension together with some other dependencies which led to the captcha not working properly anymore. Per semver, 1.5.0 should instead have been 2.0.0.

Were you maybe unaware of semver? I just wanted to provide feedback so maybe such a case can be prevented in the future.

Best regards!

**Comment by thomasrawiel** [comment]
Hi @lorenzulrich,

thank you for the feedback. 
I wasn't aware of the semantics but will keep that in mind for the future.

Sorry for the inconvenience

Cheers
