### ISSUE TITLE
How to set the language of the reCaptcha (v2)?

### ISSUE THREAD

**Issue by baden32** [thomasrawiel/powermailcaptcha#22]
Looks like the recaptcha integration is done without any language instruction/config.
How would it be possible to set/pass the language of the current Typo3 page?

Seems the language should be added to the javascript call

In Recaptcha.html
<script src="//www.google.com/recaptcha/api.js?hl=<mylanguage>" async defer></script>

Would it be possible to add a powermailrecaptcha settings (like sitekey) in order to define the language to "use" when reCaptcha is displayed?

Thank you in advance for your help.
Regards
Joël

**Comment by thomasrawiel** [comment]
The current sitelanguage (TwoLetterIsoCode) is automatically added to the api url if the option `plugin.tx_powermailcaptcha.settings.useSiteLanguage` is enabled (enabled by default in constants)

```
<script src="//www.google.com/recaptcha/api.js{f:if(condition: settings.powermailcaptcha.useSiteLanguage,then:'?hl={languageIso}')}" async defer></script>
```

You can disable the constant, then it will use the browser's language

Make sure to add the Typoscript include to your template (from version 1.5 and up)

**Comment by thomasrawiel** [comment]
A wild guess: Maybe you override the Page.html partial or the form controller in your template extension. See https://github.com/thomasrawiel/powermailcaptcha?tab=readme-ov-file#upgrade-from-10x-to-11x

**Comment by baden32** [comment]
Hi Thomas,
Thank you for your reply. Can you let me know the version of powermail and powermailrecaptcha you are using?
I'm using versions 10.8.0 and 5.2.1 and in the ReCaptcha.html template, I can see the following:

<div class="powermail_fieldwrap powermail_fieldwrap_type_recaptcha powermail_fieldwrap_{field.marker} {field.css} {settings.styles.framework.fieldAndLabelWrappingClasses}">
	<label class="{settings.styles.framework.labelClasses}" title="{field.description}">
		<vh:string.escapeLabels>{field.title}</vh:string.escapeLabels><span class="mandatory">*</span>
	</label>

	<div class="{settings.styles.framework.fieldWrappingClasses}">
		<f:if condition="{settings.recaptcha.sitekey} != 'abcdef'">
			<f:then>
				<script src="//www.google.com/recaptcha/api.js" async defer></script>
				<div class="g-recaptcha" data-sitekey="{settings.recaptcha.sitekey}"></div>
			</f:then>
			<f:else>
				<p>
					Please register your domain to
					<a href="https://www.google.com/recaptcha/">https://www.google.com/recaptcha/</a>
					and enter your sitekey in TypoScript Constants like<br />
					plugin.tx_powermailrecaptcha.sitekey = abcdef
				</p>
			</f:else>
		</f:if>
	</div>
</div>

Is there a list of settings we can define?
Regarding the Typoscript to include to your template, I cannot see any powermailrecpatcha item:

![image](https://github.com/thomasrawiel/powermailcaptcha/assets/3597655/9000aadb-8c46-49d9-a73a-c71c434bda4d)

I also tried to put the ReCaptcha.html in my own web extensions, but the only file used is the one under ext/powermailrecaptcha/Resources/...

Hope you can help me.
Regards,
Joël

**Comment by thomasrawiel** [comment]
Hi Joël,

I see.
It seems you are confusing the extensions. This is EXT:powermailcaptcha

The code you have posted is from [EXT:powermailrecaptcha](https://github.com/in2code-de/powermailrecaptcha/blob/master/Resources/Private/Partials/Form/Field/Recaptcha.html)

**Comment by thomasrawiel** [comment]
No problem,

Cheers
