### ISSUE TITLE
The mail cannot be sent. Spam factor 90%

### ISSUE THREAD

**Issue by bm1-phillip** [thomasrawiel/powermailcaptcha#23]
Hello,

the Spamlevel is at around 90 %

My relevant settings:
```
plugin.tx_powermailcaptcha.captchaMethod = hcaptcha
plugin.tx_powermailcaptcha.sitekey = 1094a...
plugin.tx_powermailcaptcha.secretkey = ES_3e....
plugin.tx_powermail {
  settings.spamshield.enable = 1
  settings.setup.spamshield.factor = 85
  settings.validation.client = 1
}
```

Versions
```
TYPO3: 10.4.45
"in2code/powermail": 8.4.2
"in2code/powermail_cond": 8.2.3
"traw/powermailcaptcha": 1.1.2
```

**Comment by thomasrawiel** [comment]
Most likely a problem with your powermail setup.

Try disabling the captcha and/ or [debug the spam settings ](https://github.com/in2code-de/powermail/blob/master/Documentation/ForAdministrators/BestPractice/SpamPrevention.md#debug-and-finetune-the-spamsettings)

Maybe lower the spam indication score if the captcha fails:
`plugin.tx_powermail.settings.setup.spamshield.methods.10.indication = 7`
