### ISSUE TITLE
[Bug] Prosopo Captcha validation configuration

### ISSUE THREAD

**Issue by thomasrawiel** [thomasrawiel/powermailcaptcha#25]
@forgetso 

Your configuration for prosopo captcha in the Domain Validator seems to be wrong:
Looking at the prosopo API docs, I'm guessing it should be like in my last commit in the develop branch

Can you test and confirm this?

**Comment by thomasrawiel** [comment]
Probably yea, do you still have that problem with the latest version? (2.1.1) @Schwuuuuup

**Comment by forgetso** [comment]
Hey, sorry I've only just seen this but will take a look asap. I'll update later tonight

**Comment by forgetso** [comment]
Your fix looks correct. The body is now

```
{
  token: "...",
  secret: "..."
}
```
I'll make a note to update here if we make any more changes to the API! Apologies again for not seeing this sooner.

**Comment by thomasrawiel** [comment]
No problem, thanks for taking a look

**Comment by Schwuuuuup** [comment]
Sorry, I seem to have had notifications turned off and did not realize that there were replies.

I still have this problem and had version 2.1.1 in the first place:
  https://dev.rrzk.uni-koeln.de/captchatest
  
 When I disable the capcha, the form works fine

**Comment by thomasrawiel** [comment]
@Schwuuuuup I see the problem, will push a fix soon

**Comment by thomasrawiel** [comment]
@Schwuuuuup please update to `2.1.2` and report back if your issue is solved

**Comment by thomasrawiel** [comment]
> Your fix looks correct. The body is now
> 
> ```
> {
>   token: "...",
>   secret: "..."
> }
> ```
> 
> I'll make a note to update here if we make any more changes to the API! Apologies again for not seeing this sooner.



fyi: Your service actually returns a different result than all the other services
```

if($this->configuration['captchaMethod'] === 'procaptcha') {
      return $result->status === 'ok' && $result->verified;
}
        
return (bool)$result->success;
```

**Comment by forgetso** [comment]
@thomasrawiel  thanks very much for fixing!
