### ISSUE TITLE
Extension does not work with EXT:powermail 8

### ISSUE THREAD

**Issue by georgringer** [thomasrawiel/powermailcaptcha#8]
The extension does not work with powermail version 8.4.1 because the method declaration does *not* match!

See
https://github.com/einpraegsam/powermail/blob/8.4.2/Classes/Controller/FormController.php#L64
```php
public function formAction(): void
```

and version 9+
```php
public function formAction(): ResponseInterface
```

as a solution I suggest to drop the formcontroller usage and use the signal `BeforeRenderView` of ext:powermail instead of using XCLASS!

**Comment by georgringer** [comment]
I can provide a PR either tomorrow or next week

**Comment by thomasrawiel** [comment]
Thanks, [1.1.2](https://github.com/thomasrawiel/powermailcaptcha/releases/tag/1.1.2) should work with powermail 8 now

**Comment by georgringer** [comment]
hey @thomasrawiel,

sorry but this can't work with PHP8 and Powermail v8 because the differences mentioned in https://github.com/thomasrawiel/powermailcaptcha/issues/8#issue-1735919550 still are valid! there are different return types which break with PHP8
